'use client'
import Navbar from "./(main)/components/Navbar/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Contact from "./(main)/components/ Contact/Contact";
import { DarkModeProvider } from "./(main)/components/DarkModeProvider";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <DarkModeProvider>
      <html lang="en">
        <body className={inter.className}>
          <div
            className={`${
              darkMode ? "dark:bg-black dark:text-white" : ""
            } `}
          >
            <Navbar darkMode={darkMode} setDarkMode={setDarkMode} />
            {children}
            <Contact />
          </div>
        </body>
      </html>
    </DarkModeProvider>
  );
}

