import Navbar from './(main)/components/Navbar/Navbar';
import './globals.css';
import { Inter } from 'next/font/google';
import Contact from "./(main)/components/ Contact/Contact";
import { DarkModeProvider } from "./(main)/components/DarkModeProvider";

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface RootLayoutProps {
  children: React.ReactNode;
}


export default function RootLayout({ children }: RootLayoutProps) {

  return (
    <DarkModeProvider>
      <html lang="en">
        <body className={inter.className}>  
          <Navbar/>
          {children}
          <Contact />
        </body>
      </html>
    </DarkModeProvider>
  );
}
